[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow-array = "52.2.0"
async-trait = "0.1"
anyhow = "1.0"
dotenv = "0.15.0"
git2 = "0.18"
lancedb = "0.10.0"
octocrab = "0.32"
rig-core = { git = "https://github.com/0xPlaygrounds/rig" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serenity = { version = "0.12", features = [
    "client",
    "gateway",
    "rustls_backend",
    "model",
    "cache",
] }
tokio = { version = "1.36", features = ["full"] }
walkdir = "2.4"
