[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow-array = "53.3.0"
async-trait = "0.1"
anyhow = "1.0"
clap = { version = "4.5.21", features = ["derive", "env"] }
chrono = "0.4.20-rc.1"
dotenv = "0.15.0"
git2 = "0.18.0"
lancedb = "0.13.0"
octocrab = "0.42.0"
rig-core = { git = "https://github.com/0xPlaygrounds/rig" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serenity = { version = "0.12", features = [
    "client",
    "gateway",
    "rustls_backend",
    "model",
    "cache",
] }
tokio = { version = "1.36", features = ["full"] }
toml = "0.8.19"
walkdir = "2.4"
